/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.*;
/**
 *
 * @author Veymar Montaño Colqu
 */
public class VistaResultadoMuestra extends javax.swing.JPanel {

    /**
     * Creates new form VistaResultadoMuestra
     */
    private Muestra muestra;
    
    public VistaResultadoMuestra() {
        initComponents();
    }
    
    public VistaResultadoMuestra(Muestra muestra) {
        initComponents();
        setVisible(true);
        this.muestra = muestra;
        actualizarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        label_tipoMuestra = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_solucionBuffer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_tipoTest = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_InstrumentoUtilizado = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_VolumenMuestra = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_ResultadoFinal = new javax.swing.JLabel();
        panel_observacionesMuestra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_observacionesMuestra = new javax.swing.JTextArea();
        btn_mostrarDetalles = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        label_codigoMuestra = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        label_fechaExtraccion = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("TIPO DE MUESTRA:");

        label_tipoMuestra.setText("Tipo de muestra");

        jLabel3.setText("SOLUCION BUFFER:");

        label_solucionBuffer.setText("Solucion buffer");

        jLabel5.setText("TIPO DE TEST:");

        label_tipoTest.setText("Tipo de Test.");

        jLabel7.setText("INSTRUMENTO UTILIZADO:");

        label_InstrumentoUtilizado.setText("Instrumento Utilizado");

        jLabel9.setText("VOLUMEN(ml):");

        label_VolumenMuestra.setText("volMues");

        jLabel12.setText("RESULTADO FINAL:");

        label_ResultadoFinal.setText("Resultado Final.");

        panel_observacionesMuestra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Observaciones")));

        txtA_observacionesMuestra.setColumns(20);
        txtA_observacionesMuestra.setRows(5);
        jScrollPane1.setViewportView(txtA_observacionesMuestra);

        javax.swing.GroupLayout panel_observacionesMuestraLayout = new javax.swing.GroupLayout(panel_observacionesMuestra);
        panel_observacionesMuestra.setLayout(panel_observacionesMuestraLayout);
        panel_observacionesMuestraLayout.setHorizontalGroup(
            panel_observacionesMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_observacionesMuestraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_observacionesMuestraLayout.setVerticalGroup(
            panel_observacionesMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_observacionesMuestraLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_mostrarDetalles.setText("Mostrar Detalles");
        btn_mostrarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarDetallesActionPerformed(evt);
            }
        });

        jLabel14.setText("CODIGO DE MUESTRA:");

        label_codigoMuestra.setText("Cod Muestra");

        jLabel16.setText("FECHA DE EXTRACCION:");

        label_fechaExtraccion.setText("fechaExtrac");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_InstrumentoUtilizado, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_ResultadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_codigoMuestra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_VolumenMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_fechaExtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_tipoTest, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_solucionBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_mostrarDetalles)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_tipoMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(panel_observacionesMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(label_codigoMuestra)
                    .addComponent(jLabel16)
                    .addComponent(label_fechaExtraccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(label_tipoMuestra))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(label_tipoTest)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(label_InstrumentoUtilizado)
                    .addComponent(jLabel3)
                    .addComponent(label_solucionBuffer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(label_ResultadoFinal)
                    .addComponent(jLabel9)
                    .addComponent(label_VolumenMuestra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_observacionesMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_mostrarDetalles))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarDetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mostrarDetallesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrarDetalles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_InstrumentoUtilizado;
    private javax.swing.JLabel label_ResultadoFinal;
    private javax.swing.JLabel label_VolumenMuestra;
    private javax.swing.JLabel label_codigoMuestra;
    private javax.swing.JLabel label_fechaExtraccion;
    private javax.swing.JLabel label_solucionBuffer;
    private javax.swing.JLabel label_tipoMuestra;
    private javax.swing.JLabel label_tipoTest;
    private javax.swing.JPanel panel_observacionesMuestra;
    private javax.swing.JTextArea txtA_observacionesMuestra;
    // End of variables declaration//GEN-END:variables

    private void actualizarDatos()
    {
        label_codigoMuestra.setText(muestra.getIdMuestra());
        label_tipoMuestra.setText(muestra.getTipoMuestra());
        label_tipoTest.setText(muestra.getTipoTest());
        label_InstrumentoUtilizado.setText(muestra.getInstrumento());
        label_solucionBuffer.setText(muestra.getSolucionBuffer());
        label_ResultadoFinal.setText(muestra.getResultadoFinal());
        label_VolumenMuestra.setText(Double.toString(muestra.getVolMuestra()));
        txtA_observacionesMuestra.setText(muestra.getObservaciones());
    }
}
