/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.MuestraCtrl;
import controlador.PacienteCtrl;
import controlador.TratamientoCtrl;
import java.awt.Label;
import java.awt.Panel;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import modelo.Muestra;
import modelo.Paciente;

/**
 *
 * @author Marcelo
 */
public class HistorialPaciente extends javax.swing.JFrame {

    /** Controllers */
    private final PacienteCtrl pacienteCtrl;
    private final MuestraCtrl muestraCtrl;
    private final TratamientoCtrl tratamientoCtrl;
    
    /** General Properties */
    private DefaultComboBoxModel pacientes;
    private List<Paciente> listaPacientes;
    private Paciente paciente;


    /**
     * Creates new form HistorialPaciente
     */
    public HistorialPaciente() {
        pacienteCtrl = new PacienteCtrl();
        muestraCtrl = new MuestraCtrl();
        tratamientoCtrl = new TratamientoCtrl();

        initComponents();
        ipanel_Tratamientos.setLayout(new BoxLayout(ipanel_Tratamientos, BoxLayout.Y_AXIS));
        setComboBoxPacientes();
        setTratamientos();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_NombreV = new javax.swing.JLabel();
        lbl_ApPatV = new javax.swing.JLabel();
        lbl_ApMatV = new javax.swing.JLabel();
        lbl_FNacV = new javax.swing.JLabel();
        lbl_TipoSangreV = new javax.swing.JLabel();
        lbl_CIV = new javax.swing.JLabel();
        lbl_TelfV = new javax.swing.JLabel();
        lbl_DirV = new javax.swing.JLabel();
        lbl_CorreoV = new javax.swing.JLabel();
        cmb_Pacientes = new javax.swing.JComboBox();
        panel_Tratamientos = new javax.swing.JScrollPane();
        ipanel_Tratamientos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Paciente"));

        jLabel1.setText("ID Paciente :");

        jLabel2.setText("Nombre :");

        jLabel3.setText("Direccion :");

        jLabel4.setText("Telefono :");

        jLabel5.setText("Ap. Paterno :");

        jLabel6.setText("Ap, Materno :");

        jLabel7.setText("CI :");

        jLabel8.setText("Correo :");

        jLabel9.setText("Fecha Nacimiento :");

        jLabel10.setText("Tipo Sangre :");

        cmb_Pacientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Pacientes.setSelectedItem("");
        cmb_Pacientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_PacientesItemStateChanged(evt);
            }
        });
        cmb_Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_PacientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(33, 33, 33)
                        .addComponent(lbl_TipoSangreV))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_NombreV)
                            .addComponent(lbl_ApPatV)
                            .addComponent(lbl_ApMatV)
                            .addComponent(cmb_Pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_FNacV))))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(49, 49, 49)
                        .addComponent(lbl_CIV)
                        .addContainerGap(207, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_TelfV))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_CorreoV))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_DirV))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_Pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_NombreV)
                            .addComponent(jLabel7)
                            .addComponent(lbl_CIV)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_ApPatV))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbl_ApMatV)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TelfV)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_DirV))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lbl_FNacV)
                            .addComponent(jLabel8)
                            .addComponent(lbl_CorreoV))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_TipoSangreV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Tratamientos.setBorder(javax.swing.BorderFactory.createTitledBorder("Tratamientos"));

        javax.swing.GroupLayout ipanel_TratamientosLayout = new javax.swing.GroupLayout(ipanel_Tratamientos);
        ipanel_Tratamientos.setLayout(ipanel_TratamientosLayout);
        ipanel_TratamientosLayout.setHorizontalGroup(
            ipanel_TratamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        ipanel_TratamientosLayout.setVerticalGroup(
            ipanel_TratamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        panel_Tratamientos.setViewportView(ipanel_Tratamientos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Tratamientos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Tratamientos, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_PacientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_PacientesItemStateChanged
        
        // Clear all components.
        ipanel_Tratamientos.removeAll();
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String id = (String) cmb_Pacientes.getSelectedItem();
            paciente = pacienteCtrl.buscarPaciente(id);
            setCamposPaciente(paciente);
            setTratamientos();
        }
    }//GEN-LAST:event_cmb_PacientesItemStateChanged

    private void cmb_PacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_PacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_PacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_Pacientes;
    private javax.swing.JPanel ipanel_Tratamientos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ApMatV;
    private javax.swing.JLabel lbl_ApPatV;
    private javax.swing.JLabel lbl_CIV;
    private javax.swing.JLabel lbl_CorreoV;
    private javax.swing.JLabel lbl_DirV;
    private javax.swing.JLabel lbl_FNacV;
    private javax.swing.JLabel lbl_NombreV;
    private javax.swing.JLabel lbl_TelfV;
    private javax.swing.JLabel lbl_TipoSangreV;
    private javax.swing.JScrollPane panel_Tratamientos;
    // End of variables declaration//GEN-END:variables

    private void setComboBoxPacientes() {

        pacientes = new DefaultComboBoxModel();
        listaPacientes = pacienteCtrl.getAllPacientes();

        for (int i = 0; i < listaPacientes.size(); i++) {
            pacientes.addElement(listaPacientes.get(i).getIdPaciente());
        }

        cmb_Pacientes.setModel(pacientes);
        cmb_Pacientes.setMaximumRowCount(4);
        
        // sets the initial paciente as default
        if (listaPacientes.size() > 0) {
            paciente = pacienteCtrl.buscarPaciente(listaPacientes.get(0).getIdPaciente());
        }
    }

    private void setCamposPaciente(Paciente paciente) {
        lbl_NombreV.setText(paciente.getNombre());
        lbl_ApPatV.setText(paciente.getApPaterno());
        lbl_ApMatV.setText(paciente.getApMaterno());
        lbl_FNacV.setText(paciente.getFnac());
        lbl_CIV.setText(paciente.getCi());
        lbl_TipoSangreV.setText(paciente.getTipoSangre());
        lbl_CorreoV.setText(paciente.getCorreo());
        lbl_TelfV.setText(paciente.getTelefono());
        lbl_DirV.setText(paciente.getDireccion());
    }

    private void setTratamientos() {
        if (paciente != null) {
            List<Muestra> muestras = muestraCtrl.getAllMuestras(paciente.getIdPaciente());

            if (!muestras.isEmpty()) {
                for (Muestra muestra : muestras) {
                    TratamientoPanel tp = new TratamientoPanel(muestra);
                    tp.setVisible(true);
                    ipanel_Tratamientos.add(tp);
                }
            } else {
                ipanel_Tratamientos.add(new Label("No hay muestras ni tratamientos para este paciente."));
            }
        }
    }
}
