/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import dao.*;
import dao.Factory.*;
import modelo.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author Veymar Montaño Colqu
 */
public class Historial extends javax.swing.JFrame {
    
    private String idPaciente;
    private final MuestraCtrl muestraCtrl;
    private final PacienteCtrl pacienteCtrl;
    private final EnsayoCtrl ensayoCtrl;
    
    /**
     * Creates new form Historial
     */
    public Historial() {
        initComponents();
        muestraCtrl = new MuestraCtrl();
        pacienteCtrl = new PacienteCtrl();
        ensayoCtrl = new EnsayoCtrl();
    }
    
    public Historial(String idPaciente) {
        initComponents();
        muestraCtrl = new MuestraCtrl();
        pacienteCtrl = new PacienteCtrl();
        ensayoCtrl = new EnsayoCtrl();
        this.idPaciente = idPaciente;
        actualizarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Historial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollpane_HInformeMuestras = new javax.swing.JScrollPane();
        panel_muestras = new javax.swing.JPanel();
        panel_HIdentificacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label_HNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_HEdad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_HSexo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_HNacionalidad = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        label_HEstadoCivil = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_HOcupacion = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_HApPaterno = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        label_HApMaterno = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        label_HDireccion = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        label_HTelefono = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        label_HCi = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        label_HCorreo = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        label_HLugarRecidencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial-Resultados");

        panel_Historial.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIAL DE MUESTRAS CLINICAS");
        panel_Historial.add(jLabel1);
        jLabel1.setBounds(232, 11, 263, 17);

        scrollpane_HInformeMuestras.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORME DE MUESTRAS REALIZADAS"));

        panel_muestras.setLayout(new java.awt.GridLayout(1, 1, 1, 10));
        scrollpane_HInformeMuestras.setViewportView(panel_muestras);

        panel_Historial.add(scrollpane_HInformeMuestras);
        scrollpane_HInformeMuestras.setBounds(10, 210, 840, 390);

        panel_HIdentificacion.setBorder(javax.swing.BorderFactory.createTitledBorder("FICHA DE IDENTIFICACION"));

        jLabel2.setText("NOMBRE(s):");

        label_HNombre.setText("Nombres");

        jLabel4.setText("EDAD:");

        label_HEdad.setText("Edad");

        jLabel6.setText("SEXO:");

        label_HSexo.setText("Sexo");

        jLabel8.setText("NACIONALIDAD:");

        label_HNacionalidad.setText("Nacionalidad");

        jLabel10.setText("ESTADO CIVIL:");

        label_HEstadoCivil.setText("Estado Civil");

        jLabel12.setText("OCUPACION:");

        label_HOcupacion.setText("Ocupación");

        jLabel14.setText("AP. PATERNO:");

        label_HApPaterno.setText("apPaterno");

        jLabel16.setText("AP. MATERNO:");

        label_HApMaterno.setText("apMaterno");

        jLabel18.setText("DIRECCION:");

        label_HDireccion.setText("Direccion");

        jLabel20.setText("TELEFONO:");

        label_HTelefono.setText("Telefono");

        jLabel22.setText("CI.:");

        label_HCi.setText("ci.");

        jLabel24.setText("CORREO:");

        label_HCorreo.setText("Correo.");

        jLabel26.setText("LUGAR DE RECIDENCIA:");

        label_HLugarRecidencia.setText("Lugar de Recidencia");

        javax.swing.GroupLayout panel_HIdentificacionLayout = new javax.swing.GroupLayout(panel_HIdentificacion);
        panel_HIdentificacion.setLayout(panel_HIdentificacionLayout);
        panel_HIdentificacionLayout.setHorizontalGroup(
            panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                        .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(label_HNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel14))
                            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_HDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                                .addComponent(label_HApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_HApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                                .addComponent(label_HTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_HCi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_HOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                        .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6)
                                .addComponent(label_HNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addComponent(label_HEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_HLugarRecidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(label_HEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6)
                                .addGap(6, 6, 6)
                                .addComponent(label_HSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_HCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        panel_HIdentificacionLayout.setVerticalGroup(
            panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_HIdentificacionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(label_HNombre)
                    .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(label_HApPaterno))
                    .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_HApMaterno)
                        .addComponent(jLabel16)))
                .addGap(11, 11, 11)
                .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_HDireccion)
                        .addComponent(jLabel20)
                        .addComponent(label_HTelefono)
                        .addComponent(jLabel22)
                        .addComponent(label_HCi)
                        .addComponent(jLabel12)
                        .addComponent(label_HOcupacion)))
                .addGap(11, 11, 11)
                .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(label_HNacionalidad)
                    .addComponent(jLabel10)
                    .addComponent(label_HEstadoCivil)
                    .addComponent(jLabel4)
                    .addComponent(label_HEdad)
                    .addComponent(jLabel6)
                    .addComponent(label_HSexo))
                .addGap(11, 11, 11)
                .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(panel_HIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_HLugarRecidencia)
                        .addComponent(jLabel24)
                        .addComponent(label_HCorreo))))
        );

        panel_Historial.add(panel_HIdentificacion);
        panel_HIdentificacion.setBounds(10, 34, 840, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Historial, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Historial, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_HApMaterno;
    private javax.swing.JLabel label_HApPaterno;
    private javax.swing.JLabel label_HCi;
    private javax.swing.JLabel label_HCorreo;
    private javax.swing.JLabel label_HDireccion;
    private javax.swing.JLabel label_HEdad;
    private javax.swing.JLabel label_HEstadoCivil;
    private javax.swing.JLabel label_HLugarRecidencia;
    private javax.swing.JLabel label_HNacionalidad;
    private javax.swing.JLabel label_HNombre;
    private javax.swing.JLabel label_HOcupacion;
    private javax.swing.JLabel label_HSexo;
    private javax.swing.JLabel label_HTelefono;
    private javax.swing.JPanel panel_HIdentificacion;
    private javax.swing.JPanel panel_Historial;
    private javax.swing.JPanel panel_muestras;
    private javax.swing.JScrollPane scrollpane_HInformeMuestras;
    // End of variables declaration//GEN-END:variables

    private void actualizarDatos()
    {
        Paciente paciente = pacienteCtrl.buscarPaciente(idPaciente);
        establecerDatosPaciente(paciente);
        ArrayList<Muestra> muestras = (ArrayList)muestraCtrl.getAllMuestras(idPaciente);
        establecerDatosMuestra(muestras);
    }
    
    private void establecerDatosPaciente(Paciente paciente)
    {
        label_HNombre.setText(paciente.getNombre());
        label_HApPaterno.setText(paciente.getApPaterno());
        label_HApMaterno.setText(paciente.getApMaterno());
        label_HDireccion.setText(paciente.getDireccion());
        label_HTelefono.setText(paciente.getTelefono());
        label_HCi.setText(paciente.getCi());
        label_HCorreo.setText(paciente.getCorreo());        
    }
    
    private void establecerDatosMuestra(ArrayList<Muestra> muestras)
    {
        VistaResultadoMuestra auxiliar;
        ((GridLayout)panel_muestras.getLayout()).setRows(muestras.size());
        
        for(Muestra muestra:muestras)
        {
            auxiliar = new VistaResultadoMuestra(muestra);            
            panel_muestras.add(auxiliar);
            System.out.print("lo agrego");
        }
    }
}
