/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Veymar Montaño Colqu
 */
public class VistaEnsayoDetalle extends javax.swing.JPanel {

    /**
     * Creates new form VistaEnsayoDetalle
     */
    public VistaEnsayoDetalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_fechaExtraccion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_fechaGel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_tipoExtraccion = new javax.swing.JLabel();
        label_tipoGel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_numeroExtraccion = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        label_resultadoEnsayo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de ensayo"));

        jLabel1.setText("FECHA:");

        jLabel2.setText("EXTRACION:");

        label_fechaExtraccion.setText("Fecha de Extraccion");

        jLabel4.setText("GEL:");

        label_fechaGel.setText("Fecha Gel.");

        jLabel6.setText("TIPO:");

        label_tipoExtraccion.setText("Tipo de Extraccion.");

        label_tipoGel.setText("Tipo de Gel");

        jLabel9.setText("NUMERO DE EXTRACCION:");

        label_numeroExtraccion.setText("NExtraccion.");

        jLabel11.setText("RESULTADO:");

        label_resultadoEnsayo.setText("Resultado.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_fechaGel)
                                    .addComponent(label_fechaExtraccion))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_tipoGel)
                                        .addComponent(label_tipoExtraccion))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_numeroExtraccion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_resultadoEnsayo)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(label_numeroExtraccion)
                    .addComponent(jLabel11)
                    .addComponent(label_resultadoEnsayo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(label_fechaExtraccion)
                    .addComponent(label_tipoExtraccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(label_fechaGel)
                    .addComponent(label_tipoGel)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_fechaExtraccion;
    private javax.swing.JLabel label_fechaGel;
    private javax.swing.JLabel label_numeroExtraccion;
    private javax.swing.JLabel label_resultadoEnsayo;
    private javax.swing.JLabel label_tipoExtraccion;
    private javax.swing.JLabel label_tipoGel;
    // End of variables declaration//GEN-END:variables
}
